version: "3.9"

services:
  backend:
    build:
      context: ./backend/go
      dockerfile: Dockerfile
    image: clipper-backend:latest
    expose:
      - "8000"
      - "8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - REST_PORT=8000
      - GRPC_PORT=8001
      - CLIPS_DIR=/clipper/clips
      - SRC_DIR=/clipper/sources
    volumes:
      - ${HOME}/clipper/source_videos:/clipper/sources
      - ${HOME}/clipper/clips:/clipper/clips

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: clipper-frontend:latest
    ports:
      - "8080:80"
