// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package clips

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClipsClient is the client API for Clips service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClipsClient interface {
	NewClip(ctx context.Context, in *ClipsRequest, opts ...grpc.CallOption) (*ClipsResponse, error)
}

type clipsClient struct {
	cc grpc.ClientConnInterface
}

func NewClipsClient(cc grpc.ClientConnInterface) ClipsClient {
	return &clipsClient{cc}
}

func (c *clipsClient) NewClip(ctx context.Context, in *ClipsRequest, opts ...grpc.CallOption) (*ClipsResponse, error) {
	out := new(ClipsResponse)
	err := c.cc.Invoke(ctx, "/clips.Clips/NewClip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClipsServer is the server API for Clips service.
// All implementations must embed UnimplementedClipsServer
// for forward compatibility
type ClipsServer interface {
	NewClip(context.Context, *ClipsRequest) (*ClipsResponse, error)
	mustEmbedUnimplementedClipsServer()
}

// UnimplementedClipsServer must be embedded to have forward compatible implementations.
type UnimplementedClipsServer struct {
}

func (UnimplementedClipsServer) NewClip(context.Context, *ClipsRequest) (*ClipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewClip not implemented")
}
func (UnimplementedClipsServer) mustEmbedUnimplementedClipsServer() {}

// UnsafeClipsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClipsServer will
// result in compilation errors.
type UnsafeClipsServer interface {
	mustEmbedUnimplementedClipsServer()
}

func RegisterClipsServer(s grpc.ServiceRegistrar, srv ClipsServer) {
	s.RegisterService(&Clips_ServiceDesc, srv)
}

func _Clips_NewClip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipsServer).NewClip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clips.Clips/NewClip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipsServer).NewClip(ctx, req.(*ClipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Clips_ServiceDesc is the grpc.ServiceDesc for Clips service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Clips_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clips.Clips",
	HandlerType: (*ClipsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewClip",
			Handler:    _Clips_NewClip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clips/clips.proto",
}
