// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package clips

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClipServerClient is the client API for ClipServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClipServerClient interface {
	NewClip(ctx context.Context, in *ClipInfo, opts ...grpc.CallOption) (*Response, error)
}

type clipServerClient struct {
	cc grpc.ClientConnInterface
}

func NewClipServerClient(cc grpc.ClientConnInterface) ClipServerClient {
	return &clipServerClient{cc}
}

func (c *clipServerClient) NewClip(ctx context.Context, in *ClipInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/clips.ClipServer/NewClip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClipServerServer is the server API for ClipServer service.
// All implementations must embed UnimplementedClipServerServer
// for forward compatibility
type ClipServerServer interface {
	NewClip(context.Context, *ClipInfo) (*Response, error)
	mustEmbedUnimplementedClipServerServer()
}

// UnimplementedClipServerServer must be embedded to have forward compatible implementations.
type UnimplementedClipServerServer struct {
}

func (UnimplementedClipServerServer) NewClip(context.Context, *ClipInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewClip not implemented")
}
func (UnimplementedClipServerServer) mustEmbedUnimplementedClipServerServer() {}

// UnsafeClipServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClipServerServer will
// result in compilation errors.
type UnsafeClipServerServer interface {
	mustEmbedUnimplementedClipServerServer()
}

func RegisterClipServerServer(s grpc.ServiceRegistrar, srv ClipServerServer) {
	s.RegisterService(&ClipServer_ServiceDesc, srv)
}

func _ClipServer_NewClip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipServerServer).NewClip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clips.ClipServer/NewClip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipServerServer).NewClip(ctx, req.(*ClipInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// ClipServer_ServiceDesc is the grpc.ServiceDesc for ClipServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClipServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clips.ClipServer",
	HandlerType: (*ClipServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewClip",
			Handler:    _ClipServer_NewClip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clips/clips.proto",
}
